name: Gen
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  gen:
    name: Gen DB
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Use Node 18
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run
        shell: bash
        run: |
          date > LOG.json
          #node gen.js

      - name: Commit
        run: |
          git config --global user.name "Andrea Marchesini"
          git config --global user.email "baku@mozilla.com"
          git add LOG.json pre.json
          git commit -m "Stats updated"
          git push -fq origin main
